# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01

# kwabo specific
local_server: "http://10.0.0.212:8000//"
split_ratio: .25
random_state: 10
josiah_label: 0
amaka_label: 1
derrick_label: 2
others_label: 3

